seed: 1
use_wb: 0
# save_dir: /home/phillipmiao/holo_stage/test_output/

# task
num_negative: 64
strict_negative: yes
adversarial_temperature: 1
metric: [mr, mrr, hits@1, hits@3, hits@10, hits@10_50]

# optimizer
optimizer: Adam
lr: 5.0e-3

# train
batch_size: 32
epochs: 30
eval_interval: 3


dataset:
  name: Indecommerce
  num_rows: 1000
  root: /home/phillipmiao/holo_stage/processed_data/row1000_train4/
  # version: v1
  csv_file_path: /home/phillipmiao/holo_stage/data/
  train_categories: [appliances.kitchen.refrigerators, furniture.bedroom.bed, electronics.smartphone, apparel.shoes]
  test_categories: [computers.desktop]
  # all available categories under E-commerce dataset: computers.desktop, appliances.kitchen.refrigerators, furniture.bedroom.bed, electronics.smartphone, apparel.shoes
  # all available categories under HM dataset: hm

edgegraph:
  final_model: rgcn
  nbf:
    input_dim: 256 # node feature dimension
    hidden_dims: [256, 256, 256, 256, 256, 256]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: no
  rgcn:
    input_dim: 256
    hidden_dims: [256, 256, 256, 256, 256, 256]
    aggregate_func: mean
    short_cut: yes
    layer_norm: yes
    dependent: no

  edge_embed_dim: 256
  edge_embed_num_layers: 1
  edge_model: GINEConv # or GCNConv (but only works with use_p_value=False)
  use_p_value: True
